<?php

namespace Matriphe\Larinfo\Windows;

class WindowsNoComNet
{
    public function getOS()
    {
        return parent::getOS(); // TODO: Change the autogenerated stub
    }

    public function getDistro()
    {
        return parent::getDistro(); // TODO: Change the autogenerated stub
    }

    public function getKernel()
    {
        return parent::getKernel(); // TODO: Change the autogenerated stub
    }

    public function getCPUArchitecture()
    {
        return parent::getCPUArchitecture(); // TODO: Change the autogenerated stub
    }

    public function getUpTime()
    {
        return parent::getUpTime(); // TODO: Change the autogenerated stub
    }

    public function getCPU()
    {
        return parent::getCPU(); // TODO: Change the autogenerated stub
    }

    public function getModel()
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

    public function getRam()
    {
        return parent::getRam(); // TODO: Change the autogenerated stub
    }

    public function getMounts()
    {
        return parent::getMounts(); // TODO: Change the autogenerated stub
    }
}
